### ISSUE TITLE
Add HUD behavior and stage status tracking

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/witch-one-homepage#14]
## Required Tasks:

- [ ] allow the game manager to track the current number of players in the stage
- [ ] add stage countdown timer
- [x] add inventory
- [ ] design inventory HUD
- [ ] track player score (kill points)

## Description:

Currently, there is no network functionality to the game, meaning that there should only be one player on screen for now. HUD should be flexible enough to be easily changed when we add proper multiplayer in the game

## Difficulty

4/10

## Estimated Implementation Time

- Optimistic - {how long this will take to finish all the subtasks at the very least}
- Normal - {how long this will take to finish all the subtasks on average work time}
- Pessimistic - {how long this will take to finish all the subtasks at most}

## Work Start Date

{when will the implementation will start}
