### ISSUE TITLE
Improve our task management system

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/witch-one-homepage#40]
## Task Description

It appears that our current task management system is ineffective in being descriptive or providing engagement to the team members. At the moment, tasks are only described during our weekly meeting, and most of the progress records are scattered around the team's network. We need a single source of information that can propagate across our team.
Ideally, we want something that can be integrated with Github, Slack, Trello, and Google Office suite. So a member can update make changes from either of the sources and see it being reflected on other sources as well.

Fortunately, we have a lot of bots that we can use. It's a matter of exactly how we should improve our organization. However, Trello may be hard as they require payment for using their webhooks.

## Subtasks

- [x] Clearly define our project milestones
- [x] Research on methods to improve our project management practices
- [x] Define a generic task model for unifying the data
- [x] Start work on implementing this so members can see and interact with tasks from Slack without having to go to other sources
- [x] Add better task templates  for GitHub

## Difficulty

9/10

## Estimated Implementation Time

- Optimistic - 1 week
- Normal - 3 weeks
- Pessimistic - more than 3 weeks

## Work Start Date

11/11/2020
