### ISSUE TITLE
[Task] Add Unity asset usage CSV export to the doc workflow

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/witch-one-homepage#44]
# Task Summary

The [Find References 2](https://assetstore.unity.com/packages/tools/utilities/find-reference-2-59092) plugin allows you to export the asset reference as a CSV.
This uses the `public static void ExportCSV(FR2_Ref[] csvSource)` function (`FR2_Export.cs:30`).
Being able to invoke this method as a unity headless script and add that to the document page could be useful.

## Subtasks

This ticket will be considered as finished when the following items are fulfilled:

- [ ] create a unity headless script that saves asset references as a csv file in the specified path
- [ ] convert the csv file into a markdown table that can be used inside `docfx`
- [ ] add a workflow to automatically generate the project asset table to the project docs

## Difficulty

9/10

## Estimated Implementation Time

> Note: the task start date is considered to be the day the ticket was opened or the next day when the dependent task was closed

- **Optimistic**: 2 weeks
- **Normal**: 20 days
- **Pessimistic**: 3 weeks
